### ISSUE TITLE
357. Magnum Weapon Problems

### ISSUE THREAD

**Issue by thepersonwhoplaysgames** [vingard/impulse-issues#19] opened 2019-02-10 17:29 UTC
**Describe the bug**
The "Fists" weap

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**impulse version (press f1 in the bottom left):**

**Lua error**
If applicable, post the error here in full.

**Additional context**

**Comment by vingard** [comment] 2019-02-10 17:31
Can you please describe the issue a bit more?

**Comment by vingard** [comment] 2019-02-10 17:35
This bug is caused by the server running NMod while your client still uses the HL2 weapons so I'll close it. Will be fixed next test. Thanks.

**Closed by vingard** 2019-02-10 17:35 UTC
